#! /bin/sh

# Start things
i3lock-bls -u "$WALLPAPER" &
feh --bg-fill $WALLPAPER &
videobg $LIVEWALL &
xss-lock -- $HOME/.bin/i3lock-bls -l dimblur &
compton -cb 
nm-applet &
redshift &
caffeine &
numlockx &
mpd &
sxhkd &
launch_polybar &
java_non_reparenting_wm_hack &

# Bspwm config
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         3
bspc config normal_border_color  "#808080"
bspc config focused_border_color "#495AFF"
bspc config window_gap           8
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true 

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config click_to_focus			 true

# Rule examples
bspc rule -a Zathura state=tiled
bspc rule -a net-minecraft-launcher-Main state=floating
bspc rule -a System-config-printer.py state=floating
bspc rule -a tilda focus=off 
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
